apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-java-environment"
spec:
  title: "Java Environment"
  description: "Overview of working on Java applications."
  duration: 30m
  publish:
    image: $(image_repository)/labs-educates-showcase/lab-java-environment-files:$(workshop_version)
  workshop:
    image: jdk17-environment:*
    files:
      - image:
          url: "$(image_repository)/labs-educates-showcase/lab-java-environment-files:$(workshop_version)"
        includePaths:
          - /resources/**
          - /workshop/**
          - /exercises/**
      - path: .m2
        image:
          url: ghcr.io/vmware-tanzu-labs/lab-spring-boot-on-k8s-maven:latest
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      files:
        enabled: true
    dashboards:
      - name: Initializr
        url: $(ingress_protocol)://initializr-$(session_namespace).$(ingress_domain)
    ingresses:
      - name: initializr
        protocol: http
        host: initializr.$(workshop_namespace).svc.cluster.local
        port: 8080
  environment:
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: initializr
          labels:
            app: initializr
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: initializr
          template:
            metadata:
              labels:
                app: initializr
            spec:
              containers:
                - name: dashboard
                  image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.2.0
                  imagePullPolicy: Always
                  ports:
                    - name: 8080-tcp
                      containerPort: 8080
                      protocol: TCP
      - apiVersion: v1
        kind: Service
        metadata:
          name: initializr
          labels:
            app: initializr
        spec:
          type: ClusterIP
          selector:
            app: initializr
          ports:
            - name: 8080-tcp
              port: 8080
              protocol: TCP
              targetPort: 8080
